### PR TITLE
Fix sort by alphabetically

### LINKED ISSUE #128: Sort by 'alphabetically' is broken
See order of resources on this image

The order right now is really random:
F
R
A

Expecting ascending order:
A
B
C

image

### PR DESCRIPTION
**Pull request by tshin7**
Resolves #128

### CODE REVIEW

**Comment by galiat** [comment]
https://github.com/codeforboston/communityconnect/search?q=organizationname&unscoped_q=organizationname

the file `src/components/ResultList.js` also used organizationName

```js
if(a.organizationname > b.organizationname) return 1
else if(a.organizationname < b.organizationname ) return -1
```

I'm at work-work  right now, but if you have the time would be worth checking to see if this also needs an update

**Comment by tshin7** [comment]
> https://github.com/codeforboston/communityconnect/search?q=organizationname&unscoped_q=organizationname
> 
> the file `src/components/ResultList.js` also used organizationName
> 
> ```js
> if(a.organizationname > b.organizationname) return 1
> else if(a.organizationname < b.organizationname ) return -1
> ```
> 
> I'm at work-work right now, but if you have the time would be worth checking to see if this also needs an update

I think that's the one I fixed.

**Comment by galiat** [comment]
ahaha. yeah, I agree. I need to stop reviewing code inbetween running builds at work-work

**Comment by tshin7** [comment]
Why can't I see the netlify deploy preview anymore? @galiat

**Comment by galiat** [comment]
not sure, but I'm gonna go head & merge this.

**Pull request merged**
