### PR TITLE
UI Changes

### PR DESCRIPTION
**Pull request by sayansaha1143**
Fixed minor UI changes.

- Search Bar moved below the header on the CardGrid #148 (Works on Mobile too)
- Changed the font size of the logo text 
- Removed the gap between Category List and Header pane #166

### CODE REVIEW

**Comment by ndesai06** [comment]
Header looks good on web. Checked Netlify preview on mobile and the "three line" drop down has moved from the header to below the "Community Connect" text. Might want to decrease the font slightly so that the drop down option stays on the top right of the mobile screen.

What the preview looks like on mobile:
img_2c708306d6e2-1

**Comment by galiat** [comment]
oh yeah. on iPhoneX its moved. On other phones it looks fine

**Comment by galiat** [comment]
Oh! the sort-by & search part look a little weird. I'd say leave that & we can fix it in another PR, probably by removing the label for sort altogether

**Comment by sayansaha1143** [comment]
Yeah I was actually trying to mess around with the search bar css to make sure it looks neat on the mobile view, but it ended up messing the rest of the components. So I figured Il just make a working PR first then look at the design later.

**Pull request merged**
