### PR TITLE
Bug/207

### PR DESCRIPTION
**Pull request by rahulmotan**
### Before submitting this PR, please use netlify to make sure:
- [x] The app looks okay on web
- [ ] The app looks okay on phone
- [x] Filter by category still works

### If you might be concerned about these things, also check:
- [ ] The app looks okay in ipad
- [ ] Search still works

### CODE REVIEW

**Comment by sayansaha1143** [comment]
It would be helpful if you could merge with the latest and resolve the conflicts for this PR.

**Comment by rahulmotan** [comment]
> It would be helpful if you could pull from the latest and resolve the conflicts for this PR.

Sure, I'll do that. Thank you.

**Comment by rahulmotan** [comment]
need approval. I have merged my changes.

**Comment by timtheguy** [comment]
Right now, some of the cards are missing the '+' button designed to add resources. Some slight changes might need to be made - since issue #207 only mentions the social media links, maybe break out the other changes into a separate issue and a separate PR. 

If we ever need to revert the change, it will be more clear how they made it into the code base!

**Pull request merged**
