### PR TITLE
This creates add sorting functionality by distance.

### PR DESCRIPTION
**Pull request by microcat49**
This adds the functionality to get the current location and sort by which location are closest.

### CODE REVIEW

**Comment by sayansaha1143** [comment]
@ndesai06 I think you would need to add me as an admin to be able to resolve conflicts and merge files.

**Comment by ndesai06** [comment]
@sayansaha1143 just changed yours to admin access!

**Comment by ndesai06** [comment]
The Netlify preview is still showing the same sorted list for both "Alphabetically" and by "Distance". However, the distance itself is showing up correctly in the info box!

**Comment by sayansaha1143** [comment]
Sorting looks good @microcat49.

**Pull request merged**
