### PR TITLE
Add scrollbar to and resize category dropdown when window height is t…

### LINKED ISSUE #137: No-Scroll on Categories Dropdown
The Category dropdown on the header stops at "Hotlines" on normal view of Chrome. User would have to zoom out to see the full list. If the Category list had a scroll bar, then the full list could be viewed at normal view.

screen shot 2018-12-14 at 11 24 07 am

### PR DESCRIPTION
**Pull request by tshin7**
Resolves #137

### CODE REVIEW

**Comment by tshin7** [comment]
@Khoawala I was going something like that at first, but I thought having a set height wouldn't look good on all screens sizes. The set height would have to be pretty small if it's going to work on a small window height. Then the dropdown would be way too small on bigger window heights.

**Comment by Khoawala** [comment]
Can you find a way to have it auto resize based on the height of the screen?

**Comment by tshin7** [comment]
> Can you find a way to have it auto resize based on the height of the screen?

I think it's possible with javascript, but not with css. Is it okay to use inline style?

**Comment by tshin7** [comment]
> Can you find a way to have it auto resize based on the height of the screen?

@Khoawala I changed it so that now I use javascript to determine the dropdown height based off the window height. What do you think?

**Comment by Khoawala** [comment]
That is definitely excessive. I found the solution, you can just simply do "height: 50vh" which means, i think, it will be 50% of the viewport's height. More info here: https://www.w3.org/TR/css3-values/#viewport-relative-lengths
So in your css file, you can keep the overflow to be auto and the height to be #vh. Replace # with whatever height you think is appropriate.

**Pull request merged**
